import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { SupplyTable } from '../components/SupplyTable';
import { BorrowTable } from '../components/BorrowTable';
import { useAccount } from "wagmi";

const Home: NextPage = () => {
  const { address } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className='flex flex-col items-end mb-12'>
          <ConnectButton />
        </div>

        <div className='flex space-x-3 justify-center mt-12'>
          { address && (
            <>
              <SupplyTable />
              <BorrowTable />
            </>
          )}
          {
            !address && (
              <div className="flex flex-col bg-gray-900 p-6 m-12 rounded-lg shadow-lg items-center justify-center w-full h-80">
                <h2 className="text-2xl text-white font-bold mb-12">Please connect your wallet.</h2>
                <ConnectButton />
              </div>
            )
          }
        </div>
      </main>
    </div>
  );
};

export default Home;
